language: python
python:
  - 3.9
env:
  - SECRET_KEY = 'test'
services:
  - postgresql
install:
  - pipenv install
script: python run manage.py test
# after_success:
# after_failure:
# after_script:
# deploy:
#   provider: pages 
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   on:
#     branch: master