language: python
python:
  - "3.9.1"
env:
  - SECRET_KEY = 'test'
services:
  - postgresql
before_install:
  - python --version
install:
  - pipenv install
script: python manage.py test
# after_success:
# after_failure:
# after_script:
# deploy:
#   provider: pages 
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   on:
#     branch: master