# Generated by Django 3.1.4 on 2020-12-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_substitut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='substitut',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
