# Generated by Django 3.1.4 on 2021-01-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_substitut'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
